language: node_js
node_js:
- '8'
before_deploy:
- openssl aes-256-cbc -K $encrypted_03b0bb3237ea_key -iv $encrypted_03b0bb3237ea_iv
  -in client-secret.json.enc -out client-secret.json -d
deploy:
  provider: gae
  keyfile: client-secret.json
  project: good-accounts
  on: master
